### ISSUE TITLE
CORS policy error with client-javascript

### ISSUE THREAD

**Issue by wilsonmichaelunl** [onetcenter/web-services-samples#2]
I'm getting a CORS policy error when requesting  `https://services.onetcenter.org/ws/` and `https://services.onetcenter.org/ws/online/search?client` when using the example provided for the client-javascript sample.

**Comment by mansoorbilalrana** [comment]
@wilsonmichaelunl  Have you found solution for it I am facing same cors error using fetch?

**Comment by Hopper262** [comment]
@mansoorbilalrana Make sure you have the website's domain name registered in your [Web Services account settings](https://services.onetcenter.org/developer/editorigin). When you run the keyword search example, the exact string to register is shown within the page.

If you continue to have problems, please contact [O*NET Customer Service](mailto:onet@onetcenter.org).
